import {nutritionFacts} from '../public/js/food-model.js';import {calculateNutritionScore} from '../public/js/nutrition-score.js';
export const pipelineVersion=3;
export const manufacturerChips={code:'028400199636',product_name:'Sour Cream & Onion Flavored Potato Chips',brands:"Lay's",serving_size:'About 17 chips (28 g)',serving_quantity:28,allergens_tags:['en:milk'],source:{name:'PepsiCo SmartLabel',url:'https://smartlabel.pepsico.info/028400199636-0031-en-US/index.html',updated:'2025-09-05'},nutriments:{'energy-kcal_serving':160,fat_serving:10,'saturated-fat_serving':1.5,carbohydrates_serving:15,sugars_serving:2,fiber_serving:1,proteins_serving:2,sodium_serving:.2}};
export const manufacturerClassic={...manufacturerChips,code:'028400199148',product_name:'Classic Potato Chips',serving_size:'About 15 chips (28 g)',allergens_tags:[],source:{name:'PepsiCo SmartLabel',url:'https://smartlabel.pepsico.info/028400199148-0047-en-US/index.html',updated:'2025-09-05'},source_note:'Manufacturer lists total sugar as less than 1 g per serving. The calculation uses the conservative 1 g upper bound.',nutrient_bounds:{sugars:'<'},nutriments:{...manufacturerChips.nutriments,sugars_serving:1,sodium_serving:.14}};
export const canonicalBarcode=c=>String(c).replace(/^0+/,'');
export function manufacturerLookup(code){const match=[manufacturerChips,manufacturerClassic].find(p=>canonicalBarcode(code)===canonicalBarcode(p.code));return match?{...match,code}:null;}
export function manufacturerReference(code){return canonicalBarcode(code)==='28400090889'?{...manufacturerChips,code,requires_confirmation:true,source_note:'Manufacturer reference is for the same flavor in a different package (UPC 028400199636). Confirm it matches your bag before applying.'}:null;}
export function fromUSDA(f,code){
 const quantity=Number(f.servingSize),n={},keys={1008:'energy-kcal',1003:'proteins',1004:'fat',1005:'carbohydrates',1079:'fiber',2000:'sugars',1258:'saturated-fat',1093:'sodium'};
 for(const row of f.foodNutrients||[]){const key=keys[row.nutrientId||row.nutrient?.id],v=Number(row.value??row.amount);if(key&&Number.isFinite(v)&&v>=0)n[key+'_100g']=key==='sodium'?v/1000:v;}
 if(f.servingSizeUnit?.toLowerCase()==='g'&&quantity>0){for(const [key,label]of Object.entries({'energy-kcal':'calories',fat:'fat','saturated-fat':'saturatedFat',carbohydrates:'carbohydrates',fiber:'fiber',sugars:'sugars',proteins:'protein',sodium:'sodium'})){const v=f.labelNutrients?.[label]?.value;if(typeof v==='number'&&v>=0)n[key+'_serving']=key==='sodium'?v/1000:v;}}
 return {code,product_name:f.description,brands:f.brandOwner||f.brandName,serving_quantity:f.servingSizeUnit?.toLowerCase()==='g'?quantity:null,serving_size:f.servingSizeUnit?.toLowerCase()==='g'?`${quantity} g`:'',nutriments:n,allergens_tags:[],source:{name:'USDA FoodData Central',url:`https://fdc.nal.usda.gov/food-details/${f.fdcId}/nutrients`},ingredients_text:f.ingredients||'',allergens_unknown:true};
}
export async function lookupProduct(code,fetcher=fetch){
 const official=manufacturerLookup(code);if(official)return {...official,pipeline_version:pipelineVersion};
 let primary;
 try{const r=await fetcher(`https://world.openfoodfacts.org/api/v2/product/${code}.json?fields=code,product_name,brands,ingredients_text,allergens_tags,nutriments,serving_size,serving_quantity,serving_quantity_unit`,{headers:{'User-Agent':'RePlate/0.1 (household demo)'},signal:AbortSignal.timeout(7000)});if(r.ok){const result=await r.json();if(result.status===1)primary={...result.product,code,source:{name:'Open Food Facts',url:`https://world.openfoodfacts.org/product/${code}`}};}}catch{}
 if(primary&&calculateNutritionScore(primary).score!==null)return {...primary,pipeline_version:pipelineVersion};
 try{const r=await fetcher('https://api.nal.usda.gov/fdc/v1/foods/search?api_key='+encodeURIComponent(process.env.USDA_API_KEY||'DEMO_KEY'),{method:'POST',headers:{'Content-Type':'application/json','X-Api-Key':process.env.USDA_API_KEY||'DEMO_KEY'},body:JSON.stringify({query:code,dataType:['Branded'],pageSize:10}),signal:AbortSignal.timeout(6000)});if(r.ok){const result=await r.json();const exact=(result.foods||[]).find(f=>canonicalBarcode(f.gtinUpc)===canonicalBarcode(code));if(exact){const p=fromUSDA(exact,code);if(calculateNutritionScore(p).score!==null)return {...p,pipeline_version:pipelineVersion};}}}catch{}
 const reference=manufacturerReference(code);if(reference)return {...reference,pipeline_version:pipelineVersion};
 return {...(primary||{code,product_name:'Scanned Product',nutriments:{},allergens_tags:[]}),needs_label:true,pipeline_version:pipelineVersion};
}
